/** @type {import('prettier').Config} */
module.exports = {
	endOfLine: "lf",
	bracketSpacing: true,
	useTabs: true,
	arrowParens: "always",
	semi: true,
	singleQuote: false,
	tabWidth: 4,
	printWidth: 90,
	trailingComma: "all",
	importOrder: [
		"^(react/(.*)$)|^(react$)",
		"^(next/(.*)$)|^(next$)",
		"<THIRD_PARTY_MODULES>",
		"",
		"^@/config/(.*)$",
		"^@/lib/(.*)$",
		"^@/hooks/(.*)$",
		"^@/components/(.*)$",
		"^@/styles/(.*)$",
		"^@/app/(.*)$",
		"",
		"^types$",
		"^@/types/(.*)$",
		"",
		"^[./]",
	],
	importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
	importOrderTypeScriptVersion: "5.1.3",
	tailwindConfig: "./tailwind.config.js",
	tailwindFunctions: ["cn", "cva"],
	plugins: [
		// "prettier-plugin-organize-imports",
		"@ianvs/prettier-plugin-sort-imports",
		"prettier-plugin-tailwindcss",
	],
};
